version: '3.5'
services:
  salt:
    image: "janniswarnat/salt:latest"
    build: ./build_master
    ports:
      - "4505-4506:4505-4506"
      - "8000:8000"
      - "9000:9000"
      - "1234:1234"
    entrypoint: ["/bin/sh", "-c" , "mkdir -p /etc/salt/pki/master/minions && cp /tmp/raspberrypi /etc/salt/pki/master/minions && /usr/bin/supervisord"]
    networks:
      - salt
    volumes:
      - ./srv/salt:/srv/salt
    configs:
      - source: master-pem
        target: "/etc/salt/pki/master/master.pem"
      - source: master-pub
        target: "/etc/salt/pki/master/master.pub"
#      - source: minion-pub
#        target: "/tmp/docker-salt-minion"
      - source: raspberrypi-pub
        target: "/tmp/raspberrypi"
#      - source: ec2-instance-pub
#        target: "/tmp/ec2-instance"
      - source: settings-yml
        target: "/github.com/smart-proxy/config/settings.yml"
      - source: salt-yml
        target: "/github.com/smart-proxy/config/settings.d/salt.yml"
      - source: dynflow-yml
        target: "/github.com/smart-proxy/config/settings.d/dynflow.yml"
      - source: foreman-conf
        target: "/etc/salt/master.d/foreman.conf"
      - source: foreman-yaml
        target: "/etc/salt/foreman.yaml"
      - source: supervisor-conf
        target: "/etc/supervisor/supervisord.conf"
#      - source: salt-files
#        target: "/tmp/salt-files.tar.gz"
      - source: pillar-top
        target: "/srv/pillar/top.sls"
      - source: pillar-default
        target: "/srv/pillar/default.sls"
      - source: pillar-raspberrypi
        target: "/srv/pillar/raspberrypi.sls"
    environment:
      - SALT_SHARED_SECRET=sharedsecret
      - 'SALT_MASTER_CONFIG={
                              "log_level": "debug",
                              "auth.ldap.uri": "ldap://openldap-openldap-1:1389",
                              "auth.ldap.basedn": "dc=example,dc=org",
                              "auth.ldap.bindpw": "adminpassword",
                              "auth.ldap.binddn": "cn=admin,dc=example,dc=org",
                              "auth.ldap.filter": "uid={{ username }}",
                               "auth.ldap.groupou": "users",
                              "auth.ldap.groupclass": "posixGroup",
                              "auth.ldap.accountattributename": "memberUid",
                              "auth.ldap.groupattribute": "memberOf",
                              "netapi_enable_clients": ["local","wheel"],
                              "file_roots": {
                                "base": [
                                  "/srv/salt/"
                                ]
                              },
                              "pillar_roots": {
                                "base": [
                                  "/srv/pillar/"
                                ]
                              }
                            }
                            '
      - 'SALT_API_CONFIG={
                            "rest_cherrypy":{
                               "port":8000,
                               "disable_ssl":true,
                               "debug":false
                            },
                            "external_auth":{
                               "ldap":{
                                  "readers%":[
                                     {
                                        "*":[
                                           "test.ping"
                                        ]
                                     }
                                  ],
                                  "eucentraladmins%":[
                                     {
                                        "*eu-central*":[
                                           ".*"
                                        ]
                                     }
                                  ],
                                  "raspberryadmins%":[
                                     {
                                        "*raspberry*":[
                                           ".*"
                                        ]
                                     }
                                  ]
                               },
                               "sharedsecret":{
                                  "salt":[
                                     ".*",
                                     "@wheel",
                                     "@jobs",
                                     "@runner"
                                  ]
                               }
                            },
                            "sharedsecret":"sharedsecret"
                         }
                         '
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    labels:
      kompose.service.type: loadbalancer
      kompose.service.expose: "true"

#  salt-minion:
#    image: "janniswarnat/salt-minion:latest"
#    build: ./build_minion
#    entrypoint: ["salt-minion", "--log-level", "info"]
#    networks:
#      - salt
#    configs:
#      - source: minion-pem
#        target: "/etc/salt/pki/minion/minion.pem"
#      - source: minion-pub
#        target: "/etc/salt/pki/minion/minion.pub"
#      - source: minion
#        target: /etc/salt/minion

configs:
  minion-pem:
    file: "./etc_minion/salt/pki/minion/minion.pem"
  minion-pub:
    file: "./etc_minion/salt/pki/minion/minion.pub"
  master-pem:
    file: "./etc_master/salt/pki/master/master.pem"
  master-pub:
    file: "./etc_master/salt/pki/master/master.pub"
  raspberrypi-pub:
    file: "./etc_master/salt/pki/master/minions/raspberrypi"
  ec2-instance-pub:
    file: "./etc_master/salt/pki/master/minions/ec2-instance"
  minion:
    file: "./etc_minion/salt/minion"
  settings-yml:
    file: "./etc_master/foreman-proxy/settings.yml"
  salt-yml:
    file: "./etc_master/foreman-proxy/settings.d/salt.yml"
  dynflow-yml:
    file: "./etc_master/foreman-proxy/settings.d/dynflow.yml"
  foreman-conf:
    file: "./etc_master/salt/master.d/foreman.conf"
  foreman-yaml:
    file: "./etc_master/salt/foreman.yaml"
  supervisor-conf:
    file: "./etc_master/supervisor/supervisord.conf"
#  salt-files:
#    file: "./srv/salt/salt-files.tar.gz"
  pillar-top:
    file: "./srv/pillar/top.sls"
  pillar-default:
    file: "./srv/pillar/default.sls"
  pillar-raspberrypi:
    file: "./srv/pillar/raspberrypi.sls"

networks:
  salt:
    external: true

