apiVersion: v1
data:
  foreman.yaml: |+
    ---
    :proto: http
    :host: app
    :port: 3000
    # if using http with ssl certificates
    #:ssl_ca: "/var/lib/puppet/ssl/certs/ca.pem"
    #:ssl_cert: "/var/lib/puppet/ssl/private_keys/foreman.example.com.pem"
    #:ssl_key: "/var/lib/puppet/ssl/certs/foreman.example.com.pem"
    # if using http with username and password instead of https with certicates
    :username: admin
    :password: changeme
    :timeout:  60
    :salt:  /usr/local/bin/salt
    :upload_grains:  true
    #---
    #:proto: https
    #:host: foreman.example.com
    #:port: 443
    # if using http with ssl certificates
    #:ssl_ca: "/var/lib/puppet/ssl/certs/ca.pem"
    #:ssl_cert: "/var/lib/puppet/ssl/private_keys/foreman.example.com.pem"
    #:ssl_key: "/var/lib/puppet/ssl/certs/foreman.example.com.pem"
    # if using http with username and password instead of https with certicates
    #:username: admin
    #:password: changeme
    #:timeout:  10
    #:salt:  /usr/bin/salt
    #:upload_grains:  true

kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: salt
  name: foreman-yaml
