apiVersion: v1
data:
  top.sls: |
    base:
      '*':
        - default
      '*raspberrypi*':
        - raspberrypi
      '*linksmart*':
        - raspberrypi
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: salt
  name: pillar-top
